<?php
$optical = isset($optical_prescription) && is_array($optical_prescription) ? $optical_prescription : array();
$has_optical_prescription = !empty($optical);
$value = function ($key, $default = '') use ($optical) { return isset($optical[$key]) && $optical[$key] !== '' ? $optical[$key] : $default; };
$coatings = !empty($optical['coatings']) ? json_decode($optical['coatings'], true) : array();
if (!is_array($coatings)) { $coatings = array(); }
$options = array('sphere' => array('+0.00', '+0.25', '+0.50', '+1.00', '-0.25', '-0.50', '-1.00', '-2.00', '-3.00'), 'cylinder' => array('0.00', '-0.25', '-0.50', '-0.75', '-1.00', '-1.50', '-2.00', '-3.00'), 'axis' => array('0', '30', '45', '60', '90', '120', '135', '150', '180'), 'add' => array('+0.00', '+0.75', '+1.00', '+1.50', '+2.00', '+2.50', '+3.00'));
?>
<div class="col-sm-12 optical-prescription-wrapper">
    <div class="checkbox" style="margin: 12px 0 4px;"><label><input type="checkbox" class="optical-prescription-toggle" <?php echo $has_optical_prescription ? 'checked' : ''; ?>> Add optical prescription</label></div>
    <input type="hidden" name="optical_prescription_enabled" value="<?php echo $has_optical_prescription ? '1' : '0'; ?>">
    <div class="box box-info optical-prescription-panel"<?php echo $has_optical_prescription ? '' : ' style="display:none;"'; ?>>
        <div class="box-header with-border"><h3 class="box-title"><i class="fa fa-eye text-aqua"></i> Optical Prescription</h3></div>
        <div class="box-body">
            <div class="row"><div class="col-sm-12 form-group"><label>Prescription Type</label><br><?php foreach (array('spectacles' => 'Spectacles', 'contact_lens' => 'Contact Lens', 'both' => 'Both') as $key => $label) { ?><label class="radio-inline"><input type="radio" name="optical_prescription_type" value="<?php echo $key; ?>" <?php echo $value('prescription_type', 'spectacles') === $key ? 'checked' : ''; ?>> <?php echo $label; ?></label><?php } ?></div></div>
            <?php foreach (array('od' => 'OD (Right Eye)', 'os' => 'OS (Left Eye)') as $eye => $eye_label) { ?><div class="row"><div class="col-sm-12"><h5 style="font-weight:600; margin:8px 0;"><?php echo $eye_label; ?></h5></div><?php foreach (array('sphere' => 'Sphere', 'cylinder' => 'Cylinder', 'axis' => 'Axis', 'add' => 'Add') as $field => $label) { ?><div class="col-md-2 col-sm-4 col-xs-6 form-group"><label><?php echo $label; ?></label><select class="form-control" name="optical_<?php echo $eye . '_' . $field; ?>"><?php foreach ($options[$field] as $option) { $default = $field === 'axis' ? '180' : ($field === 'cylinder' ? '0.00' : '+0.00'); ?><option value="<?php echo $option; ?>" <?php echo $value($eye . '_' . $field, $default) === $option ? 'selected' : ''; ?>><?php echo $field === 'axis' ? $option . '&deg;' : $option; ?></option><?php } ?></select></div><?php } ?><div class="col-md-2 col-sm-4 col-xs-6 form-group"><label>PD</label><input class="form-control" name="optical_<?php echo $eye; ?>_pd" value="<?php echo html_escape($value($eye . '_pd', '32')); ?>"></div><div class="col-md-2 col-sm-4 col-xs-6 form-group"><label>Prism</label><input class="form-control" name="optical_<?php echo $eye; ?>_prism" value="<?php echo html_escape($value($eye . '_prism', '0')); ?>"></div></div><?php } ?>
            <div class="row optical-spectacle-details"><div class="col-sm-12"><h5 style="font-weight:600; margin:8px 0;">Spectacle Details</h5></div><div class="col-md-4 form-group"><label>Lens Type</label><select class="form-control" name="optical_lens_type"><?php foreach (array('Single Vision', 'Bifocal', 'Progressive', 'Reading') as $item) { ?><option <?php echo $value('lens_type', 'Single Vision') === $item ? 'selected' : ''; ?>><?php echo $item; ?></option><?php } ?></select></div><div class="col-md-4 form-group"><label>Lens Material</label><select class="form-control" name="optical_lens_material"><?php foreach (array('CR-39', 'Polycarbonate', 'High Index 1.67', 'Trivex') as $item) { ?><option <?php echo $value('lens_material', 'CR-39') === $item ? 'selected' : ''; ?>><?php echo $item; ?></option><?php } ?></select></div><div class="col-md-4 form-group"><label>Frame Type</label><select class="form-control" name="optical_frame_type"><?php foreach (array('Full Rim', 'Semi Rimless', 'Rimless') as $item) { ?><option <?php echo $value('frame_type', 'Full Rim') === $item ? 'selected' : ''; ?>><?php echo $item; ?></option><?php } ?></select></div><div class="col-sm-12 form-group"><label>Coatings</label><br><?php foreach (array('Anti Reflective', 'Blue Light', 'Photochromic', 'Scratch Resistant', 'Hydrophobic', 'UV Protection') as $item) { ?><label class="checkbox-inline"><input type="checkbox" name="optical_coatings[]" value="<?php echo $item; ?>" <?php echo in_array($item, $coatings, true) ? 'checked' : ''; ?>> <?php echo $item; ?></label><?php } ?></div></div>
            <div class="row optical-contact-lens-details"><div class="col-sm-12"><h5 style="font-weight:600; margin:8px 0;">Contact Lens Details</h5></div><div class="col-md-3 col-sm-6 form-group"><label>Brand</label><input class="form-control" name="optical_contact_lens_brand" value="<?php echo html_escape($value('contact_lens_brand')); ?>"></div><div class="col-md-3 col-sm-6 form-group"><label>Base Curve</label><input class="form-control" name="optical_contact_lens_base_curve" value="<?php echo html_escape($value('contact_lens_base_curve', '8.6')); ?>"></div><div class="col-md-3 col-sm-6 form-group"><label>Diameter</label><input class="form-control" name="optical_contact_lens_diameter" value="<?php echo html_escape($value('contact_lens_diameter', '14.2')); ?>"></div><div class="col-md-3 col-sm-6 form-group"><label>Replacement</label><select class="form-control" name="optical_contact_lens_replacement"><?php foreach (array('Daily', 'Bi-weekly', 'Monthly', 'Yearly') as $item) { ?><option <?php echo $value('contact_lens_replacement', 'Monthly') === $item ? 'selected' : ''; ?>><?php echo $item; ?></option><?php } ?></select></div></div>
            <div class="row"><div class="col-md-4 form-group"><label>Validity (months)</label><select class="form-control" name="optical_validity_months"><?php foreach (array(3, 6, 12, 18, 24) as $months) { ?><option value="<?php echo $months; ?>" <?php echo (int) $value('validity_months', 12) === $months ? 'selected' : ''; ?>><?php echo $months; ?> months</option><?php } ?></select></div><div class="col-md-8 form-group"><label>Notes</label><textarea class="form-control" rows="2" name="optical_notes"><?php echo html_escape($value('notes')); ?></textarea></div></div>
        </div>
    </div>
</div>
<script>
$(document).off('change.opticalPrescription', '.optical-prescription-toggle').on('change.opticalPrescription', '.optical-prescription-toggle', function () { var wrapper = $(this).closest('.optical-prescription-wrapper'); wrapper.find('input[name="optical_prescription_enabled"]').val(this.checked ? '1' : '0'); wrapper.find('.optical-prescription-panel').toggle(this.checked); }).off('change.opticalPrescriptionType', 'input[name="optical_prescription_type"]').on('change.opticalPrescriptionType', 'input[name="optical_prescription_type"]', function () { var wrapper = $(this).closest('.optical-prescription-wrapper'); wrapper.find('.optical-spectacle-details').toggle(this.value !== 'contact_lens'); wrapper.find('.optical-contact-lens-details').toggle(this.value !== 'spectacles'); }).find('input[name="optical_prescription_type"]:checked').trigger('change');
</script>
