<?php
$configs=array(
'oct'=>array('title'=>'New OCT Scan','description'=>'Record OCT scan results','back'=>'Back to OCT Scans','save'=>'Save OCT Scan','section'=>'Scan Details'),
'fundus'=>array('title'=>'New Fundus Photo','description'=>'Record fundus photography','back'=>'Back to Fundus Photos','save'=>'Save Photo','section'=>'Photo Details'),
'topography'=>array('title'=>'New Topography','description'=>'Record corneal topography','back'=>'Back to Topography','save'=>'Save Topography','section'=>'Scan Details'));
$c=$configs[$modality];
$oct_path=array('epiretinal_membrane'=>'Epiretinal Membrane','macular_hole'=>'Macular Hole','vitreomacular_traction'=>'Vitreomacular Traction','drusen'=>'Drusen','rpe_changes'=>'Rpe Changes','subretinal_fluid'=>'Subretinal Fluid','intraretinal_fluid'=>'Intraretinal Fluid','cnv'=>'Cnv','pigment_epithelial_detachment'=>'Pigment Epithelial Detachment','rnfl_thinning'=>'Rnfl Thinning');
$fundus_path=array('hemorrhages'=>'Hemorrhages','exudates'=>'Exudates','cotton_wool_spots'=>'Cotton Wool Spots','drusen'=>'Drusen','neovascularization'=>'Neovascularization','microaneurysms'=>'Microaneurysms','venous_beading'=>'Venous Beading','disc_edema'=>'Disc Edema','disc_pallor'=>'Disc Pallor','cupping'=>'Cupping','macular_hole'=>'Macular Hole','epiretinal_membrane'=>'Epiretinal Membrane','retinal_detachment'=>'Retinal Detachment','chorioretinal_atrophy'=>'Chorioretinal Atrophy');
?>
<style>.imaging-form{border-top:3px solid #0f9f91}.path-grid{display:flex;flex-wrap:wrap;gap:8px}.path-check input{display:none}.path-check span{display:block;border:1px solid #d9dde5;border-radius:6px;padding:8px 12px;cursor:pointer;font-weight:400}.path-check input:checked+span{color:#087f73;background:#e7faf7;border-color:#0f9f91}.imaging-form .box-title{font-weight:600}</style>
<div class="content-wrapper"><section class="content-header"><h1><?php echo $c['title']; ?> <small><?php echo $c['description']; ?></small></h1><ol class="breadcrumb"><li><a href="<?php echo site_url('admin/ocularimaging/'.$modality); ?>"><i class="fa fa-arrow-left"></i> <?php echo $c['back']; ?></a></li></ol></section><section class="content"><form method="post"><?php echo $this->customlib->getCSRF(); ?>
<div class="box imaging-form"><div class="box-header with-border"><h2 class="box-title">Patient</h2></div><div class="box-body"><select class="form-control select2" name="patient_id" required><option value="">Search patient by name or ID...</option><?php foreach($patients as $patient){ ?><option value="<?php echo $patient['id']; ?>" <?php echo set_value('patient_id')==$patient['id']?'selected':''; ?>><?php echo html_escape($patient['patient_name'].' (ID: '.$patient['id'].', '.$patient['gender'].', '.$patient['age'].'y)'); ?></option><?php } ?></select><?php echo form_error('patient_id','<span class="text-danger">','</span>'); ?></div></div>
<div class="box imaging-form"><div class="box-header with-border"><h2 class="box-title"><?php echo $c['section']; ?></h2></div><div class="box-body"><div class="row"><div class="form-group col-sm-<?php echo $modality==='fundus'?'3':'4'; ?>"><label>Eye</label><select class="form-control" name="eye"><option value="OD">OD (Right)</option><option value="OS">OS (Left)</option></select></div>
<?php if($modality==='oct'){ ?><div class="form-group col-sm-4"><label>Scan Type</label><select class="form-control" name="subtype"><option value="macula">Macula</option><option value="rnfl">RNFL</option><option value="optic_nerve">Optic Nerve</option><option value="anterior_segment">Anterior Segment</option></select></div><div class="form-group col-sm-4"><label>Device</label><input class="form-control" name="device" placeholder="e.g., Zeiss Cirrus"></div><?php } ?>
<?php if($modality==='fundus'){ ?><div class="form-group col-sm-3"><label>Image Type</label><select class="form-control" name="subtype"><option value="color">Color</option><option value="red_free">Red Free</option><option value="faf">FAF</option><option value="ffa">FFA</option><option value="icg">ICG</option></select></div><div class="form-group col-sm-3"><label>Field</label><select class="form-control" name="field"><option>45°</option><option>50°</option><option>Widefield</option><option>Ultra-widefield</option></select></div><div class="form-group col-sm-3"><label>Quality</label><select class="form-control" name="quality"><option value="excellent">Excellent</option><option value="good" selected>Good</option><option value="fair">Fair</option><option value="poor">Poor</option></select></div><div class="form-group col-sm-6"><label class="checkbox-inline"><input type="checkbox" name="dilated" value="1" checked> Dilated</label></div><div class="form-group col-sm-6"><label>Device</label><input class="form-control" name="device" placeholder="Camera device (e.g., Canon CR-2)"></div><?php } ?>
<?php if($modality==='topography'){ ?><div class="form-group col-sm-4"><label>Device</label><input class="form-control" name="device" placeholder="e.g., Pentacam"></div><div class="form-group col-sm-4"><label>Classification</label><select class="form-control" name="classification"><option value="normal">Normal</option><option value="suspect">Suspect</option><option value="keratoconus">Keratoconus</option><option value="post_lasik">Post-LASIK</option><option value="irregular">Irregular</option></select></div><?php } ?>
<?php if($modality==='oct'){ ?><div class="form-group col-sm-4"><label>Quality</label><select class="form-control" name="quality"><option value="excellent">Excellent</option><option value="good" selected>Good</option><option value="fair">Fair</option><option value="poor">Poor</option></select></div><?php } ?>
</div></div></div>
<?php if($modality==='oct'){ ?><div class="box imaging-form"><div class="box-header with-border"><h2 class="box-title">Measurements</h2></div><div class="box-body"><div class="row"><div class="form-group col-sm-4"><label>Central Macular Thickness (µm)</label><input type="number" min="0" step="0.1" class="form-control" name="central_macular_thickness" value="0"></div><div class="form-group col-sm-4"><label>RNFL Thickness (µm)</label><input type="number" min="0" step="0.1" class="form-control" name="rnfl_thickness" value="0"></div><div class="form-group col-sm-4"><label>GCL Thickness (µm)</label><input type="number" min="0" step="0.1" class="form-control" name="gcl_thickness" value="0"></div></div></div></div><?php } ?>
<?php if($modality==='fundus'){ ?><div class="box imaging-form"><div class="box-header with-border"><h2 class="box-title">Findings</h2></div><div class="box-body"><div class="row"><div class="form-group col-sm-6"><label>Optic Disc</label><input class="form-control" name="optic_disc" placeholder="e.g., Pink, healthy, C/D 0.3"></div><div class="form-group col-sm-6"><label>Macula</label><input class="form-control" name="macula" placeholder="e.g., Normal foveal reflex"></div><div class="form-group col-sm-6"><label>Vessels</label><input class="form-control" name="vessels" placeholder="e.g., Normal AV ratio"></div><div class="form-group col-sm-6"><label>Periphery</label><input class="form-control" name="periphery" placeholder="e.g., Flat, no breaks"></div></div></div></div><?php } ?>
<?php if($modality==='topography'){ ?><div class="box imaging-form"><div class="box-header with-border"><h2 class="box-title">Keratometry</h2></div><div class="box-body"><div class="row"><?php foreach(array('sim_k1'=>'Sim K1 (D)','sim_k2'=>'Sim K2 (D)','axis'=>'Axis (°)','astigmatism'=>'Astigmatism (D)') as $key=>$label){ ?><div class="form-group col-sm-3"><label><?php echo $label; ?></label><input type="number" step="0.01" class="form-control" name="<?php echo $key; ?>" value="0"></div><?php } ?></div></div></div><div class="box imaging-form"><div class="box-header with-border"><h2 class="box-title">Pachymetry</h2></div><div class="box-body"><div class="row"><div class="form-group col-sm-6"><label>Thinnest Point (µm)</label><input type="number" step="0.1" class="form-control" name="thinnest_point" value="0"></div><div class="form-group col-sm-6"><label>Thinnest Location</label><input class="form-control" name="thinnest_location" placeholder="e.g., Inferotemporal"></div></div></div></div><div class="box imaging-form"><div class="box-header with-border"><h2 class="box-title">Topographic Indices</h2></div><div class="box-body"><div class="row"><?php foreach(array('kpi'=>'KPI','isa'=>'ISA','sai'=>'SAI','iha'=>'IHA','ivs'=>'IVS') as $key=>$label){ ?><div class="form-group col-sm-2"><label><?php echo $label; ?></label><input type="number" step="0.01" class="form-control" name="<?php echo $key; ?>" value="0"></div><?php } ?></div></div></div><?php } ?>
<?php if($modality!=='topography'){ $paths=$modality==='oct'?$oct_path:$fundus_path; ?><div class="box imaging-form"><div class="box-header with-border"><h2 class="box-title">Pathologies Detected</h2></div><div class="box-body"><div class="path-grid"><?php foreach($paths as $key=>$label){ ?><label class="path-check"><input type="checkbox" name="pathologies[]" value="<?php echo $key; ?>"><span><?php echo $label; ?></span></label><?php } ?></div></div></div><?php } ?>
<div class="box imaging-form"><div class="box-body"><div class="form-group"><label>Interpretation</label><textarea class="form-control" rows="3" name="interpretation" placeholder="<?php echo $modality==='oct'?'Clinical interpretation of OCT findings...':'Clinical interpretation...'; ?>"></textarea></div><div class="form-group"><label><?php echo $modality==='topography'?'Notes':'Additional Notes'; ?></label><textarea class="form-control" rows="3" name="notes"></textarea></div></div><div class="box-footer text-right"><a class="btn btn-default" href="<?php echo site_url('admin/ocularimaging/'.$modality); ?>">Cancel</a> <button class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $c['save']; ?></button></div></div>
</form></section></div>
