<?php
$config = array(
    'oct' => array('title'=>'OCT Scans','description'=>'Optical Coherence Tomography scans','new'=>'New Scan','new_url'=>'oct_new','types'=>array('macula'=>'Macula','rnfl'=>'RNFL','optic_nerve'=>'Optic Nerve','anterior_segment'=>'Anterior Segment')),
    'fundus' => array('title'=>'Fundus Photos','description'=>'Fundus photography records','new'=>'New Photo','new_url'=>'fundus_new','types'=>array('color'=>'Color','red_free'=>'Red Free','faf'=>'FAF','ffa'=>'FFA','icg'=>'ICG')),
    'topography' => array('title'=>'Topography','description'=>'Corneal topography measurements','new'=>'New Topography','new_url'=>'topography_new','types'=>array())
);
$c=$config[$modality];
$labels = array('central_macular_thickness'=>'Central Macular Thickness','rnfl_thickness'=>'RNFL Thickness','gcl_thickness'=>'GCL Thickness','sim_k1'=>'Sim K1','sim_k2'=>'Sim K2','axis'=>'Axis','astigmatism'=>'Astigmatism','thinnest_point'=>'Thinnest Point','kpi'=>'KPI','isa'=>'ISA','sai'=>'SAI','iha'=>'IHA','ivs'=>'IVS');
?>
<style>
.img-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;margin-bottom:20px}.img-stat{background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:18px}.img-stat strong{font-size:28px;display:block}.img-filter{display:flex;gap:10px;margin-bottom:18px}.img-filter .search{flex:1}.img-badge{display:inline-block;border-radius:12px;padding:3px 9px;background:#e8efff;color:#345dcc;font-size:11px}.img-path{display:inline-block;background:#fff2e1;color:#a45400;padding:2px 7px;border-radius:10px;font-size:10px;margin:2px}@media(max-width:767px){.img-stats{grid-template-columns:repeat(2,1fr)}.img-filter{display:block}.img-filter>*{margin-bottom:8px}}
</style>
<div class="content-wrapper"><section class="content-header"><h1><i class="fa fa-camera"></i> <?php echo $c['title']; ?> <small><?php echo $c['description']; ?></small></h1></section><section class="content"><?php echo $this->session->flashdata('msg'); ?>
<div class="img-stats">
<?php if($modality==='oct'){ ?><div class="img-stat"><small>Total Scans</small><strong><?php echo $stats['total']; ?></strong></div><div class="img-stat"><small>Macula Scans</small><strong><?php echo $stats['macula']; ?></strong></div><div class="img-stat"><small>RNFL Scans</small><strong><?php echo $stats['rnfl']; ?></strong></div><div class="img-stat"><small>Today</small><strong><?php echo $stats['today']; ?></strong></div><?php } ?>
<?php if($modality==='fundus'){ ?><div class="img-stat"><small>Total Photos</small><strong><?php echo $stats['total']; ?></strong></div><div class="img-stat"><small>With Pathology</small><strong><?php echo $stats['pathology']; ?></strong></div><div class="img-stat"><small>This Week</small><strong><?php echo $stats['week']; ?></strong></div><div class="img-stat"><small>Today</small><strong><?php echo $stats['today']; ?></strong></div><?php } ?>
<?php if($modality==='topography'){ ?><div class="img-stat"><small>Total Scans</small><strong><?php echo $stats['total']; ?></strong></div><div class="img-stat"><small>Normal</small><strong><?php echo $stats['normal']; ?></strong></div><div class="img-stat"><small>Keratoconus</small><strong><?php echo $stats['keratoconus']; ?></strong></div><div class="img-stat"><small>This Month</small><strong><?php echo $stats['month']; ?></strong></div><?php } ?>
</div>
<div class="box box-primary"><div class="box-body"><form method="get" class="img-filter"><div class="input-group search"><input class="form-control" name="search" value="<?php echo html_escape($search); ?>" placeholder="Search by patient name or ID..."><span class="input-group-btn"><button class="btn btn-default"><i class="fa fa-search"></i></button></span></div><?php if($c['types']){ ?><select class="form-control" style="max-width:200px" name="type" onchange="this.form.submit()"><option value="">All Types</option><?php foreach($c['types'] as $key=>$label){ ?><option value="<?php echo $key; ?>" <?php echo $subtype===$key?'selected':''; ?>><?php echo $label; ?></option><?php } ?></select><?php } ?><a class="btn btn-primary" href="<?php echo site_url('admin/ocularimaging/'.$c['new_url']); ?>"><i class="fa fa-plus"></i> <?php echo $c['new']; ?></a></form>
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Patient</th><th>Eye</th><?php if($modality==='oct'){ ?><th>Scan Type</th><th>Measurements</th><th>Findings</th><?php } elseif($modality==='fundus'){ ?><th>Image Type</th><th>Findings</th><th>Pathologies</th><?php } else { ?><th>Sim K</th><th>Astigmatism</th><th>Classification</th><?php } ?><th>Date</th><th>Actions</th></tr></thead><tbody>
<?php if(!$records){ ?><tr><td colspan="7" class="text-center text-muted" style="padding:45px"><i class="fa fa-camera fa-3x"></i><h4>No imaging records found</h4><p><?php echo $c['description']; ?></p><a class="btn btn-primary" href="<?php echo site_url('admin/ocularimaging/'.$c['new_url']); ?>"><?php echo $c['new']; ?></a></td></tr><?php } ?>
<?php foreach($records as $record){ $m=json_decode($record['measurements_json'],true) ?: array(); $f=json_decode($record['findings_json'],true) ?: array(); $p=json_decode($record['pathologies_json'],true) ?: array(); ?><tr><td><a href="<?php echo site_url('admin/ocularimaging/view/'.$record['id']); ?>"><strong><?php echo html_escape($record['patient_name']); ?></strong></a><br><small class="text-muted">ID: <?php echo (int)$record['patient_no']; ?> | <?php echo html_escape($record['record_number']); ?></small></td><td><span class="img-badge"><?php echo html_escape($record['eye']); ?></span></td>
<?php if($modality==='oct'){ ?><td><?php echo isset($c['types'][$record['subtype']])?$c['types'][$record['subtype']]:ucwords(str_replace('_',' ',$record['subtype'])); ?><br><small><?php echo html_escape($record['device']); ?></small></td><td><?php foreach($m as $key=>$value){ if($value!==''){ ?><small><?php echo isset($labels[$key])?$labels[$key]:$key; ?>: <strong><?php echo html_escape($value); ?> µm</strong></small><br><?php }} ?></td><td><?php echo $p ? count($p).' detected' : 'None detected'; ?></td><?php } ?>
<?php if($modality==='fundus'){ ?><td><?php echo isset($c['types'][$record['subtype']])?$c['types'][$record['subtype']]:ucwords(str_replace('_',' ',$record['subtype'])); ?><br><small><?php echo html_escape($record['quality']); ?></small></td><td><?php echo html_escape(isset($f['optic_disc'])?$f['optic_disc']:'-'); ?></td><td><?php foreach($p as $path){ ?><span class="img-path"><?php echo ucwords(str_replace('_',' ',html_escape($path))); ?></span><?php } echo !$p?'-':''; ?></td><?php } ?>
<?php if($modality==='topography'){ ?><td><?php echo html_escape(isset($m['sim_k1'])?$m['sim_k1']:'-'); ?> / <?php echo html_escape(isset($m['sim_k2'])?$m['sim_k2']:'-'); ?> D</td><td><?php echo html_escape(isset($m['astigmatism'])?$m['astigmatism']:'-'); ?> D</td><td><span class="img-badge"><?php echo ucwords(str_replace('_',' ',html_escape($record['classification']))); ?></span></td><?php } ?>
<td><?php echo date('d M Y',strtotime($record['recorded_at'])); ?><br><small><?php echo date('h:i A',strtotime($record['recorded_at'])); ?></small></td><td><a class="btn btn-default btn-xs" href="<?php echo site_url('admin/ocularimaging/view/'.$record['id']); ?>"><i class="fa fa-eye"></i></a> <form method="post" action="<?php echo site_url('admin/ocularimaging/delete/'.$record['id']); ?>" style="display:inline" onsubmit="return confirm('Delete this imaging record?')"><?php echo $this->customlib->getCSRF(); ?><button class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></button></form></td></tr><?php } ?>
</tbody></table></div></div></div></section></div>
