<?php
$titles=array('oct'=>'OCT Scan','fundus'=>'Fundus Photo','topography'=>'Topography');
$back=array('oct'=>'OCT Scans','fundus'=>'Fundus Photos','topography'=>'Topography');
$measurements=json_decode($record['measurements_json'],true) ?: array();
$findings=json_decode($record['findings_json'],true) ?: array();
$pathologies=json_decode($record['pathologies_json'],true) ?: array();
function imaging_label($key){ return ucwords(str_replace('_',' ',$key)); }
?>
<style>.detail-card{border-top:3px solid #0f9f91}.detail-value{background:#f7f9fb;border-radius:6px;padding:12px;margin-bottom:10px}.detail-value small{display:block;color:#777}.path-tag{display:inline-block;background:#fff2e1;color:#984f00;border-radius:12px;padding:4px 9px;margin:3px}</style>
<div class="content-wrapper"><section class="content-header"><h1><?php echo $titles[$record['modality']]; ?> <small><?php echo html_escape($record['record_number']); ?></small></h1><ol class="breadcrumb"><li><a href="<?php echo site_url('admin/ocularimaging/'.$record['modality']); ?>"><i class="fa fa-arrow-left"></i> Back to <?php echo $back[$record['modality']]; ?></a></li></ol></section><section class="content"><?php echo $this->session->flashdata('msg'); ?><div class="row"><div class="col-md-8"><div class="box detail-card"><div class="box-header with-border"><h3 class="box-title">Patient Information</h3></div><div class="box-body"><div class="row"><div class="col-sm-3"><div class="detail-value"><small>Patient</small><strong><?php echo html_escape($record['patient_name']); ?></strong></div></div><div class="col-sm-3"><div class="detail-value"><small>Patient ID</small><strong><?php echo (int)$record['patient_no']; ?></strong></div></div><div class="col-sm-3"><div class="detail-value"><small>Eye</small><strong><?php echo html_escape($record['eye']); ?></strong></div></div><div class="col-sm-3"><div class="detail-value"><small>Date</small><strong><?php echo date('d M Y',strtotime($record['recorded_at'])); ?></strong></div></div></div></div></div>
<div class="box detail-card"><div class="box-header with-border"><h3 class="box-title"><?php echo $record['modality']==='fundus'?'Photo Details':'Scan Details'; ?></h3></div><div class="box-body"><dl class="dl-horizontal"><dt><?php echo $record['modality']==='fundus'?'Image Type':'Scan Type'; ?></dt><dd><?php echo ucwords(str_replace('_',' ',html_escape($record['subtype'] ?: '-'))); ?></dd><dt>Device</dt><dd><?php echo html_escape($record['device'] ?: '-'); ?></dd><?php if($record['quality']){ ?><dt>Quality</dt><dd><?php echo ucfirst(html_escape($record['quality'])); ?></dd><?php } ?><?php if($record['field_name']){ ?><dt>Field</dt><dd><?php echo html_escape($record['field_name']); ?></dd><?php } ?><?php if($record['modality']==='fundus'){ ?><dt>Dilated</dt><dd><?php echo $record['dilated']?'Yes':'No'; ?></dd><?php } ?><?php if($record['classification']){ ?><dt>Classification</dt><dd><?php echo ucwords(str_replace('_',' ',html_escape($record['classification']))); ?></dd><?php } ?></dl></div></div>
<?php if($measurements){ ?><div class="box detail-card"><div class="box-header with-border"><h3 class="box-title">Measurements</h3></div><div class="box-body"><div class="row"><?php foreach($measurements as $key=>$value){ ?><div class="col-sm-4"><div class="detail-value"><small><?php echo imaging_label($key); ?></small><strong><?php echo html_escape($value !== '' ? $value : '-'); ?></strong></div></div><?php } ?></div></div></div><?php } ?>
<?php if($findings){ ?><div class="box detail-card"><div class="box-header with-border"><h3 class="box-title">Findings</h3></div><div class="box-body"><div class="row"><?php foreach($findings as $key=>$value){ ?><div class="col-sm-6"><div class="detail-value"><small><?php echo imaging_label($key); ?></small><?php echo html_escape($value ?: '-'); ?></div></div><?php } ?></div></div></div><?php } ?>
<div class="box detail-card"><div class="box-header with-border"><h3 class="box-title">Pathologies Detected</h3></div><div class="box-body"><?php if($pathologies){ foreach($pathologies as $path){ ?><span class="path-tag"><?php echo imaging_label(html_escape($path)); ?></span><?php }}else{ ?><span class="text-muted">None detected</span><?php } ?></div></div><div class="box detail-card"><div class="box-body"><h4>Interpretation</h4><p><?php echo nl2br(html_escape($record['interpretation'] ?: 'No interpretation recorded.')); ?></p><hr><h4><?php echo $record['modality']==='topography'?'Notes':'Additional Notes'; ?></h4><p><?php echo nl2br(html_escape($record['notes'] ?: 'No additional notes.')); ?></p></div></div></div><div class="col-md-4"><div class="box box-solid"><div class="box-body text-center"><i class="fa fa-camera fa-3x text-aqua"></i><h4><?php echo $titles[$record['modality']]; ?></h4><p>Recorded by <?php echo html_escape(trim($record['doctor_name'].' '.$record['doctor_surname'])); ?></p><a class="btn btn-default btn-block" href="<?php echo site_url('admin/ocularimaging/'.$record['modality']); ?>">Back to <?php echo $back[$record['modality']]; ?></a></div></div></div></div></section></div>
