<?php
function dr_form_value($name, $fallback = '') { return set_value($name, $fallback); }
$grades = array('no_dr' => 'No DR', 'mild_npdr' => 'Mild NPDR', 'moderate_npdr' => 'Moderate NPDR', 'severe_npdr' => 'Severe NPDR', 'pdr' => 'PDR');
$dme = array('no_dme' => 'No DME', 'non_ci_dme' => 'Non-CI DME', 'ci_dme' => 'CI-DME (Clinically Significant)');
$findings = array('microaneurysms','hemorrhages','hard_exudates','cotton_wool_spots','venous_beading','irma','neovascularization','vitreous_hemorrhage','tractional_rd','macular_edema','laser_scars');
?>
<style>.dr-form-box{border-top:3px solid #7b1fa2}.dr-eye-box{background:#f7f7f9;border-radius:6px;padding:17px}.dr-finding{display:inline-block;margin:0 4px 6px 0;padding:5px 8px;border:1px solid #ddd;border-radius:3px;font-size:12px;font-weight:400}.dr-finding input{margin-right:3px}.dr-section-title{font-weight:600;color:#444;margin-bottom:15px}</style>
<div class="content-wrapper"><section class="content-header"><h1><i class="fa fa-eye"></i> New Screening <small>DR screening and management</small></h1></section><section class="content"><form method="post"><?php echo $this->customlib->getCSRF(); ?>
<div class="box dr-form-box"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-user text-purple"></i> Patient Information</h3></div><div class="box-body"><div class="form-group"><label>Patient <span class="text-danger">*</span></label><select name="patient_id" class="form-control select2" required><option value="">Search patient by name or ID...</option><?php foreach ($patients as $patient) { ?><option value="<?php echo (int)$patient['id']; ?>" <?php echo dr_form_value('patient_id') == $patient['id'] ? 'selected' : ''; ?>><?php echo html_escape($patient['patient_name'] . ' (ID: ' . $patient['id'] . ', ' . $patient['gender'] . ', ' . $patient['age'] . 'y)'); ?></option><?php } ?></select><?php echo form_error('patient_id','<span class="text-danger">','</span>'); ?></div></div></div>
<div class="box dr-form-box"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-heartbeat text-purple"></i> Diabetes History</h3></div><div class="box-body"><div class="row"><div class="form-group col-sm-4"><label>Diabetes Type</label><select class="form-control" name="diabetes_type"><option value="type1">Type 1</option><option value="type2" selected>Type 2</option><option value="gestational">Gestational</option><option value="other">Other</option></select></div><div class="form-group col-sm-4"><label>Duration of Diabetes</label><input type="number" min="0" class="form-control" name="diabetes_duration" value="<?php echo html_escape(dr_form_value('diabetes_duration',0)); ?>"></div><div class="form-group col-sm-4"><label>HbA1c</label><input type="number" min="0" step="0.1" class="form-control" name="hba1c" value="<?php echo html_escape(dr_form_value('hba1c',7)); ?>"></div></div><div class="row"><div class="form-group col-sm-3"><label>BP Systolic</label><input type="number" min="0" class="form-control" name="bp_systolic" value="<?php echo html_escape(dr_form_value('bp_systolic',120)); ?>"></div><div class="form-group col-sm-3"><label>BP Diastolic</label><input type="number" min="0" class="form-control" name="bp_diastolic" value="<?php echo html_escape(dr_form_value('bp_diastolic',80)); ?>"></div><div class="form-group col-sm-3"><label>Total Cholesterol</label><input type="number" min="0" class="form-control" name="total_cholesterol" value="<?php echo html_escape(dr_form_value('total_cholesterol',200)); ?>"></div><div class="form-group col-sm-3"><label>LDL</label><input type="number" min="0" class="form-control" name="ldl" value="<?php echo html_escape(dr_form_value('ldl',100)); ?>"></div><input type="hidden" name="hdl" value="50"><input type="hidden" name="triglycerides" value="150"><input type="hidden" name="last_hba1c_date" value="<?php echo date('Y-m-d'); ?>"></div></div></div>
<div class="box dr-form-box"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-eye text-purple"></i> Fundus Findings</h3></div><div class="box-body"><div class="row"><?php foreach (array('od' => 'OD (Right Eye)', 'os' => 'OS (Left Eye)') as $eye => $label) { ?><div class="col-sm-6"><div class="dr-eye-box"><h4><?php echo $label; ?></h4><div class="form-group"><label>DR Level</label><select class="form-control" name="<?php echo $eye; ?>_dr_level"><?php foreach($grades as $key=>$text){ ?><option value="<?php echo $key; ?>"><?php echo $text; ?></option><?php } ?></select></div><div class="form-group"><label>DME Status</label><select class="form-control" name="<?php echo $eye; ?>_dme_status"><?php foreach($dme as $key=>$text){ ?><option value="<?php echo $key; ?>"><?php echo $text; ?></option><?php } ?></select></div><label>Findings</label><div><?php foreach($findings as $finding){ ?><label class="dr-finding"><input type="checkbox" name="<?php echo $eye; ?>_findings[]" value="<?php echo $finding; ?>"> <?php echo str_replace('_',' ',$finding); ?></label><?php } ?></div></div></div><?php } ?></div></div></div>
<div class="box dr-form-box"><div class="box-header with-border"><h3 class="box-title">Imaging Results</h3></div><div class="box-body"><label class="checkbox-inline"><input type="checkbox" name="fundus_photo" value="1"> Fundus Photo</label><label class="checkbox-inline"><input type="checkbox" name="oct" value="1"> OCT</label><label class="checkbox-inline"><input type="checkbox" name="ffa" value="1"> FFA</label></div></div>
<div class="box dr-form-box"><div class="box-body"><div class="form-group"><label>Clinical Notes</label><textarea class="form-control" rows="3" name="notes" placeholder="Additional notes..."><?php echo html_escape(dr_form_value('notes')); ?></textarea></div></div><div class="box-footer text-right"><a class="btn btn-default" href="<?php echo site_url('admin/drscreening'); ?>">Cancel</a> <button class="btn btn-primary" style="background:#7b1fa2;border-color:#7b1fa2"><i class="fa fa-save"></i> Save Screening</button></div></div>
</form></section></div>
