<?php
$grades = array('no_dr' => 'No DR', 'mild_npdr' => 'Mild NPDR', 'moderate_npdr' => 'Moderate NPDR', 'severe_npdr' => 'Severe NPDR', 'pdr' => 'PDR');
function dr_grade_class($level) { return $level === 'pdr' || $level === 'severe_npdr' ? 'dr-red' : ($level === 'moderate_npdr' ? 'dr-orange' : ($level === 'mild_npdr' ? 'dr-yellow' : 'dr-green')); }
?>
<style>
.dr-stats{display:grid;grid-template-columns:repeat(7,1fr);gap:12px}.dr-stat{color:#fff;border-radius:7px;padding:15px}.dr-stat strong{display:block;font-size:25px;margin-top:4px}.dr-blue{background:linear-gradient(135deg,#42a5f5,#1976d2)}.dr-green-bg{background:linear-gradient(135deg,#66bb6a,#2e7d32)}.dr-yellow-bg{background:linear-gradient(135deg,#fbc02d,#f57f17)}.dr-orange-bg{background:linear-gradient(135deg,#fb8c00,#ef6c00)}.dr-red-bg{background:linear-gradient(135deg,#ef5350,#c62828)}.dr-darkred-bg{background:linear-gradient(135deg,#d32f2f,#8e0000)}.dr-gray-bg{background:linear-gradient(135deg,#78909c,#455a64)}.dr-ai{background:linear-gradient(90deg,#7b1fa2,#3949ab);color:#fff;border-radius:7px;padding:22px;margin:20px 0}.dr-ai h3{margin:0 0 5px}.dr-row{display:flex;align-items:center;gap:14px}.dr-icon{width:46px;height:46px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:19px}.dr-badge{display:inline-block;padding:3px 8px;border-radius:3px;font-size:11px;font-weight:600}.dr-green{background:#e8f5e9;color:#2e7d32}.dr-yellow{background:#fff8e1;color:#f57f17}.dr-orange{background:#fff3e0;color:#e65100}.dr-red{background:#ffebee;color:#b71c1c}.dr-due{background:#ff9800;color:#fff}.dr-filter-row{display:flex;gap:10px;align-items:center}.dr-muted{color:#777}@media(max-width:991px){.dr-stats{grid-template-columns:repeat(2,1fr)}.dr-filter-row{display:block}.dr-filter-row>*{margin-bottom:8px}}
</style>
<div class="content-wrapper"><section class="content-header"><h1><i class="fa fa-eye"></i> Diabetic Retinopathy Screening <small>DR screening and management</small></h1></section><section class="content">
<?php echo $this->session->flashdata('msg'); ?>
<div class="dr-stats"><div class="dr-stat dr-blue"><small>Total Diabetics</small><strong><?php echo $stats['total']; ?></strong></div><div class="dr-stat dr-green-bg"><small>No DR</small><strong><?php echo $stats['no_dr']; ?></strong></div><div class="dr-stat dr-yellow-bg"><small>Mild NPDR</small><strong><?php echo $stats['mild']; ?></strong></div><div class="dr-stat dr-orange-bg"><small>Moderate NPDR</small><strong><?php echo $stats['moderate']; ?></strong></div><div class="dr-stat dr-red-bg"><small>Severe NPDR</small><strong><?php echo $stats['severe']; ?></strong></div><div class="dr-stat dr-darkred-bg"><small>PDR</small><strong><?php echo $stats['pdr']; ?></strong></div><div class="dr-stat <?php echo $stats['due'] ? 'dr-orange-bg' : 'dr-gray-bg'; ?>"><small>Due Today</small><strong><?php echo $stats['due']; ?></strong></div></div>
<div class="dr-ai"><div class="row"><div class="col-sm-9"><h3><i class="fa fa-magic"></i> AI-Powered DR Detection</h3><div>Automated analysis of fundus images with instant grading</div></div><div class="col-sm-3 text-right"><a class="btn btn-default" style="color:#7b1fa2" href="<?php echo site_url('admin/drscreening/ai_analysis'); ?>">Start AI Screening</a></div></div></div>
<div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">All Screenings</h3></div><div class="box-body">
<form method="get" class="dr-filter-row" style="margin-bottom:18px"><div class="input-group" style="flex:1"><input name="search" value="<?php echo html_escape($search); ?>" class="form-control" placeholder="Search by patient name or ID..."><span class="input-group-btn"><button class="btn btn-default"><i class="fa fa-search"></i></button></span></div><select name="level" class="form-control" style="width:190px" onchange="this.form.submit()"><option value="">All Screenings</option><?php foreach ($grades as $key => $label) { ?><option value="<?php echo $key; ?>" <?php echo $level === $key ? 'selected' : ''; ?>><?php echo $label; ?></option><?php } ?></select><label class="btn btn-default"><input type="checkbox" name="due" value="1" <?php echo $due_only ? 'checked' : ''; ?> onchange="this.form.submit()"> Due for Screening</label><a href="<?php echo site_url('admin/drscreening/create'); ?>" class="btn btn-primary" style="background:#7b1fa2;border-color:#7b1fa2"><i class="fa fa-plus"></i> New Patient</a></form>
<?php if (!$records) { ?><div class="text-center dr-muted" style="padding:45px"><i class="fa fa-eye fa-4x"></i><h4>No screening records found</h4><p>DR screening and management</p><a href="<?php echo site_url('admin/drscreening/create'); ?>" class="btn btn-primary"><i class="fa fa-plus"></i> Add Patient</a></div><?php } ?>
<?php foreach ($records as $record) { $due = $record['next_screening'] && $record['next_screening'] <= date('Y-m-d'); $od_dme = $record['od_dme_status'] !== 'no_dme'; $os_dme = $record['os_dme_status'] !== 'no_dme'; ?>
<div class="row" style="border-top:1px solid #eee;padding:15px 0"><div class="col-md-4"><a class="dr-row" href="<?php echo site_url('admin/drscreening/view/' . $record['id']); ?>"><span class="dr-icon <?php echo dr_grade_class($record['od_dr_level'] === 'pdr' || $record['os_dr_level'] === 'pdr' ? 'pdr' : $record['od_dr_level']); ?>"><i class="fa fa-eye"></i></span><span><strong><?php echo html_escape($record['patient_name']); ?></strong> <?php if ($due) { ?><span class="dr-badge dr-due">DUE</span><?php } ?><br><small class="dr-muted">ID: <?php echo (int)$record['patient_no']; ?> | DM Duration: <?php echo (int)$record['diabetes_duration']; ?> years</small></span></a></div><div class="col-md-1 text-center"><small class="dr-muted">OD</small><br><span class="dr-badge <?php echo dr_grade_class($record['od_dr_level']); ?>"><?php echo $grades[$record['od_dr_level']]; ?></span><?php if ($od_dme) { ?><div class="text-red"><small><strong>+DME</strong></small></div><?php } ?></div><div class="col-md-1 text-center"><small class="dr-muted">OS</small><br><span class="dr-badge <?php echo dr_grade_class($record['os_dr_level']); ?>"><?php echo $grades[$record['os_dr_level']]; ?></span><?php if ($os_dme) { ?><div class="text-red"><small><strong>+DME</strong></small></div><?php } ?></div><div class="col-md-2 text-center"><small class="dr-muted">HbA1c</small><div class="<?php echo $record['hba1c'] > 7.5 ? 'text-red' : 'text-green'; ?>"><strong><?php echo $record['hba1c'] !== null ? $record['hba1c'] . '%' : '-'; ?></strong></div></div><div class="col-md-2 text-center"><small class="dr-muted">Next Screening</small><div class="<?php echo $due ? 'text-orange' : ''; ?>"><?php echo $record['next_screening'] ? date('d M Y', strtotime($record['next_screening'])) : 'Not scheduled'; ?></div></div><div class="col-md-2 text-right"><a class="btn btn-default btn-xs" href="<?php echo site_url('admin/drscreening/view/' . $record['id']); ?>" title="View"><i class="fa fa-eye"></i></a> <form method="post" action="<?php echo site_url('admin/drscreening/delete/' . $record['id']); ?>" style="display:inline" onsubmit="return confirm('Delete DR screening record for <?php echo html_escape($record['patient_name']); ?>?');"><?php echo $this->customlib->getCSRF(); ?><button class="btn btn-danger btn-xs" title="Delete"><i class="fa fa-trash"></i></button></form></div></div>
<?php } ?>
</div></div></section></div>
