<?php
function dr_view_show($value) { return $value === null || $value === '' ? '<span class="text-muted">Not recorded</span>' : nl2br(html_escape($value)); }
$grades = array('no_dr'=>'No DR','mild_npdr'=>'Mild NPDR','moderate_npdr'=>'Moderate NPDR','severe_npdr'=>'Severe NPDR','pdr'=>'PDR');
$dme = array('no_dme'=>'No DME','non_ci_dme'=>'Non-CI DME','ci_dme'=>'CI-DME (Clinically Significant)');
?>
<style>.drv-box{border-top:3px solid #7b1fa2}.drv-eye{background:#f8f8fa;border-radius:6px;padding:15px}.drv-tag{display:inline-block;padding:4px 8px;background:#ede7f6;color:#512da8;border-radius:3px;margin:2px}@media print{.main-header,.main-sidebar,.no-print{display:none!important}.content-wrapper{margin-left:0!important}}</style>
<div class="content-wrapper"><section class="content-header"><h1><i class="fa fa-eye"></i> View Screening</h1><div class="pull-right no-print" style="margin-top:-30px"><button onclick="window.print()" class="btn btn-default"><i class="fa fa-print"></i> Print</button></div></section><section class="content"><?php echo $this->session->flashdata('msg'); ?><?php if($record['next_screening'] && $record['next_screening'] <= date('Y-m-d')){ ?><div class="alert alert-warning"><i class="fa fa-exclamation-triangle"></i> This patient is due for a follow-up screening.</div><?php } ?>
<div class="box drv-box"><div class="box-header"><h3 class="box-title">Patient Information</h3></div><div class="box-body row"><div class="col-sm-4"><strong>Name</strong><br><?php echo html_escape($record['patient_name']); ?></div><div class="col-sm-2"><strong>Patient ID</strong><br><?php echo (int)$record['patient_no']; ?></div><div class="col-sm-3"><strong>Patient Details</strong><br><?php echo html_escape($record['gender'].', '.$record['age'].' years'); ?></div><div class="col-sm-3"><strong>Created</strong><br><?php echo date('d M Y, h:i A',strtotime($record['screening_date'])); ?></div></div></div>
<div class="row"><div class="col-sm-6"><div class="box drv-box"><div class="box-header"><h3 class="box-title">Diabetes History</h3></div><div class="box-body"><table class="table table-bordered"><tr><th>Diabetes Type</th><td><?php echo ucwords(str_replace('type','Type ',html_escape($record['diabetes_type']))); ?></td></tr><tr><th>Duration of Diabetes</th><td><?php echo (int)$record['diabetes_duration']; ?> years</td></tr><tr><th>HbA1c</th><td><?php echo dr_view_show($record['hba1c']); ?>%</td></tr><tr><th>Blood Pressure</th><td><?php echo dr_view_show($record['bp_systolic']).' / '.dr_view_show($record['bp_diastolic']); ?></td></tr><tr><th>LDL</th><td><?php echo dr_view_show($record['ldl']); ?></td></tr></table></div></div></div><div class="col-sm-6"><div class="box drv-box"><div class="box-header"><h3 class="box-title">Follow-up Schedule</h3></div><div class="box-body"><dl><dt>Next Screening Date</dt><dd><?php echo $record['next_screening'] ? date('d M Y',strtotime($record['next_screening'])) : 'Not scheduled'; ?></dd><dt>Frequency</dt><dd><?php echo dr_view_show($record['follow_up_frequency']); ?></dd><dt>Reason</dt><dd><?php echo dr_view_show($record['follow_up_reason']); ?></dd></dl><strong>Imaging Results</strong><p><?php echo $record['fundus_photo']?'Fundus Photo ':''; echo $record['oct']?'OCT ':''; echo $record['ffa']?'FFA':''; ?></p></div></div></div></div>
<div class="box drv-box"><div class="box-header"><h3 class="box-title">Fundus Findings</h3></div><div class="box-body"><div class="row"><?php foreach(array('od'=>'OD (Right Eye)','os'=>'OS (Left Eye)') as $eye=>$label){$findings=json_decode($record[$eye.'_findings_json'],true);if(!is_array($findings))$findings=array(); ?><div class="col-sm-6"><div class="drv-eye"><h4><?php echo $label; ?></h4><p><strong>DR Level:</strong> <?php echo $grades[$record[$eye.'_dr_level']]; ?></p><p><strong>DME:</strong> <?php echo $dme[$record[$eye.'_dme_status']]; ?></p><p><strong>Findings:</strong><br><?php if($findings){foreach($findings as $finding){ ?><span class="drv-tag"><?php echo ucwords(str_replace('_',' ',html_escape($finding))); ?></span><?php }}else{ ?><span class="text-muted">No findings documented</span><?php } ?></p></div></div><?php } ?></div><hr><strong>Clinical Notes</strong><p><?php echo dr_view_show($record['notes']); ?></p></div></div>
<div class="box drv-box"><div class="box-header"><h3 class="box-title">Screening History</h3></div><div class="box-body table-responsive"><table class="table table-striped"><thead><tr><th>Date</th><th>OD Level</th><th>OD DME</th><th>OS Level</th><th>OS DME</th><th>Notes</th></tr></thead><tbody><?php foreach($history as $item){ ?><tr><td><?php echo date('d M Y',strtotime($item['screening_date'])); ?></td><td><?php echo $grades[$item['od_dr_level']]; ?></td><td><?php echo $dme[$item['od_dme_status']]; ?></td><td><?php echo $grades[$item['os_dr_level']]; ?></td><td><?php echo $dme[$item['os_dme_status']]; ?></td><td><?php echo dr_view_show($item['notes']); ?></td></tr><?php } ?></tbody></table></div></div>
<form class="no-print" method="post" action="<?php echo site_url('admin/drscreening/delete/'.$record['id']); ?>" style="display:inline" onsubmit="return confirm('Are you sure you want to delete this DR record?');"><?php echo $this->customlib->getCSRF(); ?><button class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button></form> <a class="btn btn-default no-print" href="<?php echo site_url('admin/drscreening'); ?>"><i class="fa fa-arrow-left"></i> Back</a>
</section></div>
