<?php
$selected_type = set_value('surgery_type', $preset_type ? $preset_type : 'cataract');
$types = array('cataract'=>'Cataract Surgery','refractive'=>'Refractive Surgery','retinal'=>'Retinal Surgery','glaucoma'=>'Glaucoma Surgery','corneal'=>'Corneal Surgery','oculoplastic'=>'Oculoplastic','strabismus'=>'Strabismus','other'=>'Other');
$procedures = array(
'cataract'=>array('Phacoemulsification + IOL','ECCE + IOL','SICS + IOL','IOL Exchange','Secondary IOL'),
'refractive'=>array('LASIK','PRK','SMILE','ICL Implantation','RLE','CXL'),
'retinal'=>array('Vitrectomy','Scleral Buckle','Pneumatic Retinopexy','Membrane Peel','Laser Photocoagulation'),
'glaucoma'=>array('Trabeculectomy','Glaucoma Drainage Device','MIGS','Laser Trabeculoplasty','Cyclophotocoagulation'),
'corneal'=>array('Penetrating Keratoplasty','DSAEK','DMEK','PTK','Pterygium Excision'),
'oculoplastic'=>array('Blepharoplasty','Ptosis Repair','DCR','Orbital Surgery','Enucleation/Evisceration'),
'strabismus'=>array('Recession','Resection','Adjustable Suture'),'other'=>array('Other Procedure'));
?>
<style>.surg-form{border-top:3px solid #5b6ee1}.form-section{font-weight:600;margin:0}.conditional{display:none}</style>
<div class="content-wrapper"><section class="content-header"><h1>Schedule Surgery <small>Schedule new eye surgery</small></h1><ol class="breadcrumb"><li><a href="<?php echo site_url('admin/eyesurgery'); ?>"><i class="fa fa-arrow-left"></i> Back to Surgeries</a></li></ol></section><section class="content"><form method="post"><?php echo $this->customlib->getCSRF(); ?>
<div class="box surg-form"><div class="box-header with-border"><h3 class="box-title">Patient Information</h3></div><div class="box-body"><div class="form-group"><label>Patient <span class="text-danger">*</span></label><select class="form-control select2" name="patient_id" required><option value="">Search patient by name or ID...</option><?php foreach($patients as $patient){ ?><option value="<?php echo $patient['id']; ?>" <?php echo set_value('patient_id')==$patient['id']?'selected':''; ?>><?php echo html_escape($patient['patient_name'].' (ID: '.$patient['id'].', '.$patient['gender'].', '.$patient['age'].'y)'); ?></option><?php } ?></select><?php echo form_error('patient_id','<span class="text-danger">','</span>'); ?></div></div></div>
<div class="box surg-form"><div class="box-header with-border"><h3 class="box-title">Surgery Details</h3></div><div class="box-body"><div class="row"><div class="form-group col-sm-4"><label>Surgery Type</label><select id="surgery_type" class="form-control" name="surgery_type"><?php foreach($types as $key=>$label){ ?><option value="<?php echo $key; ?>" <?php echo $selected_type===$key?'selected':''; ?>><?php echo $label; ?></option><?php } ?></select></div><div class="form-group col-sm-4"><label>Eye</label><select class="form-control" name="eye"><option value="OD">OD (Right Eye)</option><option value="OS">OS (Left Eye)</option><option value="OU">OU (Both Eyes)</option></select></div><div class="form-group col-sm-4"><label>Procedure</label><select id="procedure_name" class="form-control" name="procedure_name" required><option value="">Select Procedure</option></select></div></div><div class="row"><div class="form-group col-sm-6"><label>Surgeon</label><select class="form-control" name="surgeon_id"><option value="">Select Surgeon</option><?php foreach($doctors as $doctor){ ?><option value="<?php echo $doctor['id']; ?>"><?php echo html_escape(trim($doctor['name'].' '.$doctor['surname'])); ?></option><?php } ?></select><small class="text-muted">If no surgeons appear, the current user will be assigned.</small></div><div class="form-group col-sm-6"><label>Anesthesia Type</label><select class="form-control" name="anesthesia_type"><option value="topical">Topical</option><option value="local">Local (Retrobulbar/Peribulbar)</option><option value="general">General</option><option value="sedation">IV Sedation</option></select></div></div></div></div>
<div class="box surg-form"><div class="box-header with-border"><h3 class="box-title">Schedule</h3></div><div class="box-body"><div class="row"><div class="form-group col-sm-4"><label>Date</label><input type="date" min="<?php echo date('Y-m-d'); ?>" class="form-control" name="surgery_date" value="<?php echo set_value('surgery_date'); ?>" required></div><div class="form-group col-sm-4"><label>Time</label><input type="time" class="form-control" name="surgery_time" value="<?php echo set_value('surgery_time'); ?>" required></div><div class="form-group col-sm-4"><label>Operating Room</label><input class="form-control" name="operating_room" placeholder="e.g., OR-1" value="<?php echo set_value('operating_room'); ?>"></div></div></div></div>
<div id="cataract_details" class="box surg-form conditional"><div class="box-header with-border"><h3 class="box-title">Cataract Surgery Details</h3></div><div class="box-body"><div class="row"><div class="form-group col-sm-3"><label>Technique</label><select class="form-control" name="cataract_technique"><option value="phaco">Phacoemulsification</option><option value="femto">Femtosecond Laser</option><option value="ecce">ECCE</option><option value="sics">SICS</option></select></div><div class="form-group col-sm-3"><label>IOL Model</label><input class="form-control" name="iol_model" placeholder="e.g. Alcon SN60WF"></div><div class="form-group col-sm-3"><label>IOL Power</label><input type="number" step="0.01" class="form-control" name="iol_power"></div><div class="form-group col-sm-3"><label>Target Refraction</label><input type="number" step="0.01" class="form-control" name="target_refraction" value="0"><a href="<?php echo site_url('admin/eyesurgery/iol_calculator'); ?>">Open IOL Calculator</a></div></div></div></div>
<div id="refractive_details" class="box surg-form conditional"><div class="box-header with-border"><h3 class="box-title">Refractive Surgery Details</h3></div><div class="box-body"><div class="row"><div class="form-group col-sm-4"><label>Procedure Type</label><select class="form-control" name="refractive_procedure"><option value="lasik">LASIK</option><option value="prk">PRK</option><option value="smile">SMILE</option></select></div><div class="form-group col-sm-4"><label>Optical Zone (mm)</label><input type="number" step="0.1" class="form-control" name="optical_zone" value="6.0"></div><div class="form-group col-sm-4"><label>Ablation Zone (mm)</label><input type="number" step="0.1" class="form-control" name="ablation_zone" value="6.5"></div></div><div class="row"><div class="form-group col-sm-4"><label>Target Sphere</label><input type="number" step="0.25" class="form-control" name="target_sphere" value="0"></div><div class="form-group col-sm-4"><label>Target Cylinder</label><input type="number" step="0.25" class="form-control" name="target_cylinder" value="0"></div><div class="form-group col-sm-4"><label>Target Axis</label><input type="number" min="0" max="180" class="form-control" name="target_axis" value="0"></div></div></div></div>
<div class="box surg-form"><div class="box-body"><div class="form-group"><label>Pre-Op Notes</label><textarea class="form-control" rows="3" name="pre_op_notes" placeholder="Pre-operative instructions, special considerations..."><?php echo set_value('pre_op_notes'); ?></textarea></div></div><div class="box-footer text-right"><a class="btn btn-default" href="<?php echo site_url('admin/eyesurgery'); ?>">Cancel</a> <button class="btn btn-primary" id="submit_btn"><i class="fa fa-calendar-check-o"></i> Schedule Surgery</button></div></div>
</form></section></div>
<script>
(function(){var all=<?php echo json_encode($procedures); ?>,type=document.getElementById('surgery_type'),proc=document.getElementById('procedure_name');function refresh(){var list=all[type.value]||[],current=<?php echo json_encode(set_value('procedure_name')); ?>;proc.innerHTML='<option value="">Select Procedure</option>';list.forEach(function(p){var o=document.createElement('option');o.value=p;o.textContent=p;if(p===current)o.selected=true;proc.appendChild(o)});document.getElementById('cataract_details').style.display=type.value==='cataract'?'block':'none';document.getElementById('refractive_details').style.display=type.value==='refractive'?'block':'none'}type.addEventListener('change',refresh);refresh()})();
</script>
