<?php
$types = array('cataract'=>'Cataract','refractive'=>'Refractive','retinal'=>'Retinal','glaucoma'=>'Glaucoma','oculoplastic'=>'Oculoplastic','corneal'=>'Corneal');
$statuses = array('scheduled'=>'Scheduled','in_progress'=>'In Progress','completed'=>'Completed','cancelled'=>'Cancelled');
$icons = array('cataract'=>'&#128142;','refractive'=>'&#127919;','retinal'=>'&#128065;','glaucoma'=>'&#128308;','oculoplastic'=>'&#10024;','corneal'=>'&#128309;','strabismus'=>'&#8596;');
?>
<style>
.surg-stats,.surg-quick{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;margin-bottom:20px}.surg-stat,.surg-card{background:#fff;border:1px solid #e6e8ee;border-radius:8px;padding:18px}.surg-stat strong{font-size:27px;display:block}.surg-card{display:flex;align-items:center;gap:14px;color:#333}.surg-card:hover{border-color:#5b6ee1;box-shadow:0 2px 8px #ddd}.surg-icon{font-size:28px;width:45px;text-align:center}.surg-row{border-top:1px solid #eee;padding:15px 0;display:flex;align-items:center}.surg-badge{display:inline-block;padding:4px 9px;border-radius:12px;font-size:11px;font-weight:600;text-transform:capitalize}.st-scheduled{background:#e8efff;color:#315ecc}.st-completed{background:#e7f7ee;color:#25834c}.st-cancelled{background:#fdeaea;color:#b93535}.st-in_progress{background:#fff4da;color:#916500}.surg-filter{display:grid;grid-template-columns:2fr 1fr 1fr 1fr auto;gap:10px}.today-tag{background:#fee2e2;color:#b91c1c;font-size:10px;padding:2px 6px;border-radius:8px}@media(max-width:991px){.surg-stats,.surg-quick{grid-template-columns:repeat(2,1fr)}.surg-filter{grid-template-columns:1fr}.surg-row{display:block}}
</style>
<div class="content-wrapper"><section class="content-header"><h1><i class="fa fa-medkit"></i> Eye Surgery <small>Surgical procedures management</small></h1><ol class="breadcrumb"><li><a class="btn btn-primary btn-sm" href="<?php echo site_url('admin/eyesurgery/create'); ?>"><i class="fa fa-plus"></i> Schedule Surgery</a></li></ol></section><section class="content">
<?php echo $this->session->flashdata('msg'); ?>
<div class="surg-stats"><div class="surg-stat"><small>Today's Surgeries</small><strong><?php echo $stats['today']; ?></strong><span class="text-muted">Today</span></div><div class="surg-stat"><small>Scheduled</small><strong><?php echo $stats['scheduled']; ?></strong></div><div class="surg-stat"><small>Completed</small><strong><?php echo $stats['completed']; ?></strong></div><div class="surg-stat"><small>Total Procedures</small><strong><?php echo $stats['total']; ?></strong></div></div>
<div class="surg-quick"><a class="surg-card" href="<?php echo site_url('admin/eyesurgery/create?type=cataract'); ?>"><span class="surg-icon">&#128142;</span><span><strong>Cataract</strong><br><small>Schedule Surgery</small></span></a><a class="surg-card" href="<?php echo site_url('admin/eyesurgery/create?type=refractive'); ?>"><span class="surg-icon">&#127919;</span><span><strong>LASIK/PRK</strong><br><small>Refractive procedure</small></span></a><a class="surg-card" href="<?php echo site_url('admin/eyesurgery/create?type=retinal'); ?>"><span class="surg-icon">&#128065;</span><span><strong>Retinal</strong><br><small>Vitreoretinal surgery</small></span></a><a class="surg-card" href="<?php echo site_url('admin/eyesurgery/iol_calculator'); ?>"><span class="surg-icon">&#128290;</span><span><strong>IOL Calculator</strong><br><small>Calculate lens power</small></span></a></div>
<div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">All Surgeries</h3></div><div class="box-body"><form method="get" class="surg-filter" style="margin-bottom:18px"><input class="form-control" name="search" value="<?php echo html_escape($filters['search']); ?>" placeholder="Search by patient name or surgery type..."><select class="form-control" name="type"><option value="">All Types</option><?php foreach($types as $key=>$label){ ?><option value="<?php echo $key; ?>" <?php echo $filters['type']===$key?'selected':''; ?>><?php echo $label; ?></option><?php } ?></select><select class="form-control" name="status"><option value="">All Status</option><?php foreach($statuses as $key=>$label){ ?><option value="<?php echo $key; ?>" <?php echo $filters['status']===$key?'selected':''; ?>><?php echo $label; ?></option><?php } ?></select><input type="date" class="form-control" name="date" value="<?php echo html_escape($filters['date']); ?>"><button class="btn btn-default"><i class="fa fa-filter"></i> Filter</button></form>
<?php if (!$records) { ?><div class="text-center text-muted" style="padding:50px"><i class="fa fa-medkit fa-4x"></i><h4>No surgeries found</h4><p>Get started by scheduling your first surgery</p><a class="btn btn-primary" href="<?php echo site_url('admin/eyesurgery/create'); ?>">Schedule Surgery</a></div><?php } ?>
<?php foreach($records as $record){ ?><div class="surg-row row"><div class="col-md-4"><span class="surg-icon" style="float:left;margin-right:10px"><?php echo isset($icons[$record['surgery_type']])?$icons[$record['surgery_type']]:'&#128300;'; ?></span><a href="<?php echo site_url('admin/eyesurgery/view/'.$record['id']); ?>"><strong><?php echo html_escape($record['patient_name']); ?></strong></a> <?php if(substr($record['surgery_date'],0,10)===date('Y-m-d')){ ?><span class="today-tag">TODAY</span><?php } ?><br><small class="text-muted"><?php echo html_escape($record['surgery_number']); ?> | ID: <?php echo (int)$record['patient_no']; ?></small><br><small><?php echo html_escape($record['procedure_name']); ?></small></div><div class="col-md-2"><strong><?php echo isset($types[$record['surgery_type']])?$types[$record['surgery_type']]:ucfirst($record['surgery_type']); ?></strong><br><small><?php echo html_escape($record['eye']); ?></small></div><div class="col-md-2"><span class="surg-badge st-<?php echo $record['status']; ?>"><?php echo isset($statuses[$record['status']])?$statuses[$record['status']]:$record['status']; ?></span></div><div class="col-md-2"><strong><?php echo date('d M Y',strtotime($record['surgery_date'])); ?></strong><br><small><?php echo date('h:i A',strtotime($record['surgery_date'])); ?></small></div><div class="col-md-1"><small>Surgeon</small><br><?php echo html_escape(trim($record['surgeon_name'].' '.$record['surgeon_surname'])); ?></div><div class="col-md-1 text-right"><a class="btn btn-default btn-xs" href="<?php echo site_url('admin/eyesurgery/view/'.$record['id']); ?>"><i class="fa fa-eye"></i></a> <form method="post" action="<?php echo site_url('admin/eyesurgery/delete/'.$record['id']); ?>" style="display:inline" onsubmit="return confirm('Delete this surgery?')"><?php echo $this->customlib->getCSRF(); ?><button class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></button></form></div></div><?php } ?>
</div></div></section></div>
