<?php
$is_edit = !empty($record['id']);
function gl_value($record, $key, $fallback = '') { return set_value($key, isset($record[$key]) ? $record[$key] : $fallback); }
$risk_values = json_decode(isset($record['risk_factors_json']) ? $record['risk_factors_json'] : '', true); if (!is_array($risk_values)) { $risk_values = array(); }
$posted_risks = $this->input->post('risk_factors', true); if (is_array($posted_risks)) { $risk_values = $posted_risks; }
$medications = json_decode(isset($record['medications_json']) ? $record['medications_json'] : '', true); if (!is_array($medications)) { $medications = array(); }
$posted_meds = $this->input->post('medications', true); if (is_array($posted_meds)) { $medications = $posted_meds; }
$types = array('poag' => 'POAG - Primary Open Angle', 'pacg' => 'PACG - Primary Angle Closure', 'ntg' => 'NTG - Normal Tension', 'secondary' => 'Secondary Glaucoma', 'congenital' => 'Congenital', 'suspect' => 'Glaucoma Suspect', 'oht' => 'Ocular Hypertension');
$risks = array('elevated_iop' => 'Elevated IOP', 'thin_cornea' => 'Thin Cornea', 'high_myopia' => 'High Myopia', 'diabetes' => 'Diabetes', 'hypertension' => 'Hypertension', 'migraine' => 'Migraine', 'sleep_apnea' => 'Sleep Apnea', 'steroid_use' => 'Steroid Use');
?>
<style>.gl-form-box{border-top:3px solid #536dfe}.gl-eye{background:#f7f9fc;border:1px solid #e4e8ef;border-radius:4px;padding:15px;margin-bottom:12px}.gl-risk{display:inline-block;margin:0 8px 8px 0;padding:8px 12px;border:1px solid #ddd;border-radius:4px;background:#fafafa}.gl-med-row{background:#f8fafc;border:1px solid #e1e5ea;padding:12px 5px 0;margin:0 0 10px;border-radius:4px}.gl-med-row .remove-med{margin-top:25px}.gl-heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}</style>
<div class="content-wrapper">
    <section class="content-header"><h1><i class="fa fa-heartbeat"></i> <?php echo $is_edit ? 'Edit' : 'New'; ?> Glaucoma Record <small>Glaucoma patient management and monitoring</small></h1></section>
    <section class="content"><form method="post" id="glaucomaForm"><?php echo $this->customlib->getCSRF(); ?>
        <div class="box gl-form-box"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-user text-blue"></i> Patient Information</h3></div><div class="box-body row">
            <div class="form-group col-sm-8"><label>Patient <span class="text-danger">*</span></label><select name="patient_id" class="form-control select2" required><option value="">Search and select a patient...</option><?php foreach ($patients as $patient) { ?><option value="<?php echo (int) $patient['id']; ?>" <?php echo gl_value($record, 'patient_id') == $patient['id'] ? 'selected' : ''; ?>><?php echo html_escape($patient['patient_name'] . ' (ID: ' . $patient['id'] . ', ' . $patient['gender'] . ', ' . $patient['age'] . 'y)'); ?></option><?php } ?></select><?php echo form_error('patient_id', '<span class="text-danger">', '</span>'); ?></div>
        </div></div>
        <div class="box gl-form-box"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-stethoscope text-blue"></i> Diagnosis</h3></div><div class="box-body row">
            <div class="form-group col-sm-4"><label>Glaucoma Type <span class="text-danger">*</span></label><select class="form-control" name="glaucoma_type" required><?php foreach ($types as $key => $label) { ?><option value="<?php echo $key; ?>" <?php echo gl_value($record, 'glaucoma_type', 'poag') === $key ? 'selected' : ''; ?>><?php echo $label; ?></option><?php } ?></select></div>
            <div class="form-group col-sm-4"><label>Severity <span class="text-danger">*</span></label><select class="form-control" name="severity" required><?php foreach (array('suspect' => 'Suspect', 'mild' => 'Mild', 'moderate' => 'Moderate', 'severe' => 'Severe', 'end_stage' => 'End Stage') as $key => $label) { ?><option value="<?php echo $key; ?>" <?php echo gl_value($record, 'severity', 'mild') === $key ? 'selected' : ''; ?>><?php echo $label; ?></option><?php } ?></select></div>
            <div class="form-group col-sm-4"><label>Diagnosis Date <span class="text-danger">*</span></label><input type="date" class="form-control" name="diagnosis_date" required value="<?php echo html_escape(gl_value($record, 'diagnosis_date', date('Y-m-d'))); ?>"></div>
            <div class="col-sm-12"><label class="checkbox-inline"><input type="checkbox" name="family_history" value="1" <?php echo gl_value($record, 'family_history') ? 'checked' : ''; ?>> Family history of glaucoma</label><hr><label>Risk Factors</label><div><?php foreach ($risks as $key => $label) { ?><label class="gl-risk"><input type="checkbox" name="risk_factors[]" value="<?php echo $key; ?>" <?php echo in_array($key, $risk_values, true) ? 'checked' : ''; ?>> <?php echo $label; ?></label><?php } ?></div></div>
        </div></div>
        <div class="box gl-form-box"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-tachometer text-blue"></i> Intraocular Pressure</h3></div><div class="box-body">
            <div class="row"><div class="col-sm-6"><h4>Current IOP</h4><div class="row"><div class="form-group col-xs-6"><label>OD (mmHg)</label><input type="number" step="0.1" min="0" class="form-control" name="iop_od" value="<?php echo html_escape(set_value('iop_od')); ?>"></div><div class="form-group col-xs-6"><label>OS (mmHg)</label><input type="number" step="0.1" min="0" class="form-control" name="iop_os" value="<?php echo html_escape(set_value('iop_os')); ?>"></div><div class="form-group col-xs-6"><label>Method</label><select class="form-control" name="iop_method"><?php foreach (array('goldmann' => 'Goldmann', 'nct' => 'NCT', 'icare' => 'iCare', 'tono_pen' => 'Tono-Pen') as $key => $label) { ?><option value="<?php echo $key; ?>"><?php echo $label; ?></option><?php } ?></select></div><div class="form-group col-xs-6"><label>Time</label><input type="datetime-local" class="form-control" name="measured_at" value="<?php echo date('Y-m-d\TH:i'); ?>"></div></div></div>
                <div class="col-sm-6"><h4>Target IOP</h4><div class="row"><div class="form-group col-xs-6"><label>OD Target (mmHg)</label><input type="number" step="0.1" min="0" class="form-control" name="target_iop_od" value="<?php echo html_escape(gl_value($record, 'target_iop_od', 16)); ?>"></div><div class="form-group col-xs-6"><label>OS Target (mmHg)</label><input type="number" step="0.1" min="0" class="form-control" name="target_iop_os" value="<?php echo html_escape(gl_value($record, 'target_iop_os', 16)); ?>"></div></div></div></div>
        </div></div>
        <div class="box gl-form-box"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-eye text-blue"></i> Optic Nerve Assessment</h3></div><div class="box-body"><div class="row">
            <?php foreach (array('od' => 'Right Eye (OD)', 'os' => 'Left Eye (OS)') as $eye => $label) { ?><div class="col-sm-6"><div class="gl-eye"><h4><?php echo $label; ?></h4><div class="form-group"><label>Cup-to-Disc Ratio</label><input type="number" step="0.1" min="0" max="1" name="cdr_<?php echo $eye; ?>" class="form-control" value="<?php echo html_escape(gl_value($record, 'cdr_' . $eye, 0.3)); ?>"></div><div class="form-group"><label>Rim Thinning</label><select class="form-control" name="rim_thinning_<?php echo $eye; ?>"><?php foreach (array('none' => 'None', 'superior' => 'Superior', 'inferior' => 'Inferior', 'temporal' => 'Temporal', 'diffuse' => 'Diffuse') as $key => $text) { ?><option value="<?php echo $key; ?>" <?php echo gl_value($record, 'rim_thinning_' . $eye, 'none') === $key ? 'selected' : ''; ?>><?php echo $text; ?></option><?php } ?></select></div><label class="checkbox-inline"><input type="checkbox" name="disc_hemorrhage_<?php echo $eye; ?>" value="1" <?php echo gl_value($record, 'disc_hemorrhage_' . $eye) ? 'checked' : ''; ?>> Disc Hemorrhage</label><label class="checkbox-inline"><input type="checkbox" name="nfl_defect_<?php echo $eye; ?>" value="1" <?php echo gl_value($record, 'nfl_defect_' . $eye) ? 'checked' : ''; ?>> NFL Defect</label></div></div><?php } ?>
        </div></div></div>
        <div class="box gl-form-box"><div class="box-body"><div class="gl-heading"><h4><i class="fa fa-medkit text-blue"></i> Current Medications</h4><button type="button" id="addMedication" class="btn btn-default btn-sm"><i class="fa fa-plus"></i> Add Medication</button></div><div id="medicationRows"><?php foreach ($medications as $i => $med) { ?><div class="gl-med-row medication-row row"><div class="form-group col-sm-4"><label>Medication</label><input class="form-control" name="medications[<?php echo $i; ?>][name]" value="<?php echo html_escape($med['name']); ?>"></div><div class="form-group col-sm-2"><label>Dosage</label><input class="form-control" name="medications[<?php echo $i; ?>][dosage]" value="<?php echo html_escape($med['dosage']); ?>"></div><div class="form-group col-sm-2"><label>Frequency</label><select class="form-control" name="medications[<?php echo $i; ?>][frequency]"><?php foreach (array('qd','bid','tid','qhs') as $freq) { ?><option <?php echo $med['frequency'] === $freq ? 'selected' : ''; ?>><?php echo strtoupper($freq); ?></option><?php } ?></select></div><div class="form-group col-sm-2"><label>Eye</label><select class="form-control" name="medications[<?php echo $i; ?>][eye]"><?php foreach (array('OU','OD','OS') as $eye) { ?><option <?php echo $med['eye'] === $eye ? 'selected' : ''; ?>><?php echo $eye; ?></option><?php } ?></select></div><div class="col-sm-2"><button type="button" class="btn btn-danger btn-sm remove-med"><i class="fa fa-trash"></i></button></div></div><?php } ?></div>
            <div class="row"><div class="form-group col-sm-4"><label>Progression Status</label><select class="form-control" name="progression_status"><option value="stable" <?php echo gl_value($record, 'progression_status', 'stable') === 'stable' ? 'selected' : ''; ?>>Stable</option><option value="suspected_progression" <?php echo gl_value($record, 'progression_status') === 'suspected_progression' ? 'selected' : ''; ?>>Suspected Progression</option><option value="definite_progression" <?php echo gl_value($record, 'progression_status') === 'definite_progression' ? 'selected' : ''; ?>>Definite Progression</option></select></div><div class="form-group col-sm-4"><label>Next Visit</label><input type="date" class="form-control" name="next_visit" value="<?php echo html_escape(gl_value($record, 'next_visit')); ?>"></div><div class="form-group col-sm-12"><label>Clinical Notes</label><textarea class="form-control" rows="3" name="notes" placeholder="Additional clinical notes..."><?php echo html_escape(gl_value($record, 'notes')); ?></textarea></div></div>
        </div><div class="box-footer text-right"><a href="<?php echo site_url('admin/glaucoma'); ?>" class="btn btn-default">Cancel</a> <button class="btn btn-primary" type="submit"><i class="fa fa-save"></i> Save Record</button></div></div>
    </form></section>
</div>
<script>(function($){var i=<?php echo count($medications); ?>;function row(n){return '<div class="gl-med-row medication-row row"><div class="form-group col-sm-4"><label>Medication</label><input class="form-control" name="medications['+n+'][name]" list="glaucomaDrops" placeholder="Latanoprost 0.005%"></div><div class="form-group col-sm-2"><label>Dosage</label><input class="form-control" name="medications['+n+'][dosage]" placeholder="1 drop"></div><div class="form-group col-sm-2"><label>Frequency</label><select class="form-control" name="medications['+n+'][frequency]"><option>QD</option><option>BID</option><option>TID</option><option>QHS</option></select></div><div class="form-group col-sm-2"><label>Eye</label><select class="form-control" name="medications['+n+'][eye]"><option>OU</option><option>OD</option><option>OS</option></select></div><div class="col-sm-2"><button type="button" class="btn btn-danger btn-sm remove-med"><i class="fa fa-trash"></i></button></div></div>';}$('#addMedication').click(function(){$('#medicationRows').append(row(i++));});$(document).on('click','.remove-med',function(){$(this).closest('.medication-row').remove();});})(jQuery);</script>
<datalist id="glaucomaDrops"><option>Latanoprost 0.005%</option><option>Timolol 0.5%</option><option>Brimonidine 0.2%</option><option>Dorzolamide 2%</option><option>Bimatoprost 0.01%</option><option>Travoprost 0.004%</option><option>Combigan</option><option>Cosopt</option><option>Simbrinza</option></datalist>
