<style>.iop-card{border-left:4px solid #3c8dbc}.iop-value{font-size:18px;font-weight:600}.iop-controlled{color:#00a65a}.iop-uncontrolled{color:#dd4b39}.iop-borderline{color:#f39c12}</style>
<div class="content-wrapper">
    <section class="content-header"><h1><i class="fa fa-line-chart"></i> IOP Tracking <small>Monitor intraocular pressure against patient targets</small></h1></section>
    <section class="content">
        <div class="row"><div class="col-sm-4"><div class="box iop-card"><div class="box-body"><span class="pull-right fa fa-users fa-2x text-blue"></span><span class="text-muted">Total Patients</span><div class="iop-value"><?php echo $stats['total']; ?></div></div></div></div><div class="col-sm-4"><div class="box iop-card" style="border-color:#00a65a"><div class="box-body"><span class="pull-right fa fa-arrow-down fa-2x iop-controlled"></span><span class="text-muted">Controlled</span><div class="iop-value iop-controlled"><?php echo $stats['controlled']; ?></div></div></div></div><div class="col-sm-4"><div class="box iop-card" style="border-color:#dd4b39"><div class="box-body"><span class="pull-right fa fa-arrow-up fa-2x iop-uncontrolled"></span><span class="text-muted">Uncontrolled</span><div class="iop-value iop-uncontrolled"><?php echo $stats['uncontrolled']; ?></div></div></div></div></div>
        <div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">IOP History</h3><div class="box-tools"><a href="<?php echo site_url('admin/glaucoma'); ?>" class="btn btn-default btn-sm"><i class="fa fa-arrow-left"></i> Glaucoma Center</a></div></div><div class="box-body">
            <form method="get" class="row" style="margin-bottom:15px"><div class="col-sm-6"><div class="input-group"><input name="search" value="<?php echo html_escape($search); ?>" class="form-control" placeholder="Search by patient name or ID..."><span class="input-group-btn"><button class="btn btn-default"><i class="fa fa-search"></i></button></span></div></div><div class="col-sm-3"><select name="iop_control" class="form-control" onchange="this.form.submit()"><option value="">All Patients</option><option value="controlled" <?php echo $iop_control === 'controlled' ? 'selected' : ''; ?>>Controlled</option><option value="uncontrolled" <?php echo $iop_control === 'uncontrolled' ? 'selected' : ''; ?>>Uncontrolled</option></select></div></form>
            <div class="table-responsive"><table class="table table-striped table-hover"><thead><tr><th>Patient</th><th>Type</th><th>Last Reading</th><th>IOP OD</th><th>IOP OS</th><th>Target OD</th><th>Target OS</th><th>Control</th><th></th></tr></thead><tbody>
                <?php if (!$records) { ?><tr><td colspan="9" class="text-center text-muted">No IOP records found.</td></tr><?php } ?>
                <?php foreach ($records as $record) { $od_bad = $record['latest_iop_od'] !== null && $record['target_iop_od'] !== null && $record['latest_iop_od'] > $record['target_iop_od']; $os_bad = $record['latest_iop_os'] !== null && $record['target_iop_os'] !== null && $record['latest_iop_os'] > $record['target_iop_os']; ?>
                    <tr><td><strong><?php echo html_escape($record['patient_name']); ?></strong><br><small>ID: <?php echo (int) $record['patient_no']; ?></small></td><td><?php echo strtoupper(html_escape($record['glaucoma_type'])); ?></td><td><?php echo $record['latest_iop_at'] ? date('d M Y, h:i A', strtotime($record['latest_iop_at'])) : '-'; ?></td><td class="iop-value <?php echo $od_bad ? 'iop-uncontrolled' : ($record['latest_iop_od'] !== null ? 'iop-controlled' : ''); ?>"><?php echo $record['latest_iop_od'] !== null ? $record['latest_iop_od'] : '-'; ?></td><td class="iop-value <?php echo $os_bad ? 'iop-uncontrolled' : ($record['latest_iop_os'] !== null ? 'iop-controlled' : ''); ?>"><?php echo $record['latest_iop_os'] !== null ? $record['latest_iop_os'] : '-'; ?></td><td><?php echo $record['target_iop_od'] !== null ? $record['target_iop_od'] : '-'; ?></td><td><?php echo $record['target_iop_os'] !== null ? $record['target_iop_os'] : '-'; ?></td><td><?php if ($record['latest_iop_od'] === null && $record['latest_iop_os'] === null) { ?><span class="label label-default">No Data</span><?php } else { ?><span class="label <?php echo ($od_bad || $os_bad) ? 'label-danger' : 'label-success'; ?>"><?php echo ($od_bad || $os_bad) ? 'Uncontrolled' : 'Controlled'; ?></span><?php } ?></td><td><a class="btn btn-default btn-xs" href="<?php echo site_url('admin/glaucoma/view/' . $record['id']); ?>"><i class="fa fa-eye"></i></a></td></tr>
                <?php } ?>
            </tbody></table></div>
        </div></div>
    </section>
</div>
