<?php
function gl_show($value) { return $value === null || $value === '' ? '<span class="text-muted">Not recorded</span>' : nl2br(html_escape($value)); }
$types = array('poag' => 'Primary Open-Angle Glaucoma', 'pacg' => 'Primary Angle-Closure Glaucoma', 'ntg' => 'Normal Tension Glaucoma', 'secondary' => 'Secondary Glaucoma', 'congenital' => 'Congenital Glaucoma', 'suspect' => 'Glaucoma Suspect', 'oht' => 'Ocular Hypertension');
$risks = json_decode($record['risk_factors_json'], true); if (!is_array($risks)) { $risks = array(); }
$medications = json_decode($record['medications_json'], true); if (!is_array($medications)) { $medications = array(); }
?>
<style>.gl-detail-box{border-top:3px solid #536dfe}.gl-kpi{font-size:26px;font-weight:600}.gl-target{color:#536dfe}.gl-high{color:#dd4b39}.gl-tag{display:inline-block;padding:4px 9px;background:#eef0ff;color:#3949ab;border-radius:3px;margin:2px}.gl-detail dt{color:#777;margin-top:10px}.gl-detail dd{font-size:15px}@media print{.main-header,.main-sidebar,.content-header .pull-right,.no-print{display:none!important}.content-wrapper{margin-left:0!important}}</style>
<div class="content-wrapper">
    <section class="content-header"><h1><i class="fa fa-heartbeat"></i> Glaucoma Record <small><?php echo html_escape($record['patient_name']); ?></small></h1><div class="pull-right no-print" style="margin-top:-30px"><button class="btn btn-default" onclick="window.print()"><i class="fa fa-print"></i> Print</button> <a class="btn btn-primary" href="<?php echo site_url('admin/glaucoma/edit/' . $record['id']); ?>"><i class="fa fa-pencil"></i> Edit</a></div></section>
    <section class="content"><?php echo $this->session->flashdata('msg'); ?>
        <div class="box gl-detail-box"><div class="box-body"><div class="row"><div class="col-sm-4"><strong>Patient</strong><br><?php echo html_escape($record['patient_name']); ?> (ID: <?php echo (int) $record['patient_id']; ?>)</div><div class="col-sm-2"><strong>Patient Details</strong><br><?php echo html_escape($record['gender'] . ', ' . $record['age'] . ' years'); ?></div><div class="col-sm-3"><strong>Diagnosis</strong><br><?php echo isset($types[$record['glaucoma_type']]) ? $types[$record['glaucoma_type']] : html_escape($record['glaucoma_type']); ?> — <?php echo ucwords(str_replace('_', ' ', html_escape($record['severity']))); ?></div><div class="col-sm-3"><strong>Doctor</strong><br><?php echo html_escape(trim($record['doctor_name'] . ' ' . $record['doctor_surname'])); ?></div></div></div></div>
        <div class="row"><div class="col-sm-4"><div class="box"><div class="box-body text-center"><span class="text-muted">Latest IOP OD</span><div class="gl-kpi <?php echo $record['latest_iop_od'] > $record['target_iop_od'] ? 'gl-high' : ''; ?>"><?php echo $record['latest_iop_od'] !== null ? $record['latest_iop_od'] . ' mmHg' : '-'; ?></div><small class="gl-target">Target <?php echo gl_show($record['target_iop_od']); ?></small></div></div></div><div class="col-sm-4"><div class="box"><div class="box-body text-center"><span class="text-muted">Latest IOP OS</span><div class="gl-kpi <?php echo $record['latest_iop_os'] > $record['target_iop_os'] ? 'gl-high' : ''; ?>"><?php echo $record['latest_iop_os'] !== null ? $record['latest_iop_os'] . ' mmHg' : '-'; ?></div><small class="gl-target">Target <?php echo gl_show($record['target_iop_os']); ?></small></div></div></div><div class="col-sm-4"><div class="box"><div class="box-body text-center"><span class="text-muted">Overall Status</span><div class="gl-kpi" style="font-size:20px"><?php echo ucwords(str_replace('_', ' ', html_escape($record['progression_status']))); ?></div><small>Next visit: <?php echo $record['next_visit'] ? date('d M Y', strtotime($record['next_visit'])) : 'Not scheduled'; ?></small></div></div></div></div>
        <div class="row"><div class="col-sm-6"><div class="box gl-detail-box"><div class="box-header"><h3 class="box-title">Optic Nerve Assessment</h3></div><div class="box-body"><table class="table table-bordered"><tr><th></th><th>OD</th><th>OS</th></tr><tr><td>Cup-to-Disc Ratio</td><td><?php echo gl_show($record['cdr_od']); ?></td><td><?php echo gl_show($record['cdr_os']); ?></td></tr><tr><td>Rim Thinning</td><td><?php echo gl_show(ucwords($record['rim_thinning_od'])); ?></td><td><?php echo gl_show(ucwords($record['rim_thinning_os'])); ?></td></tr><tr><td>Disc Hemorrhage</td><td><?php echo $record['disc_hemorrhage_od'] ? 'Yes' : 'No'; ?></td><td><?php echo $record['disc_hemorrhage_os'] ? 'Yes' : 'No'; ?></td></tr><tr><td>NFL Defect</td><td><?php echo $record['nfl_defect_od'] ? 'Yes' : 'No'; ?></td><td><?php echo $record['nfl_defect_os'] ? 'Yes' : 'No'; ?></td></tr></table></div></div></div><div class="col-sm-6"><div class="box gl-detail-box"><div class="box-header"><h3 class="box-title">Risk Factors & Notes</h3></div><div class="box-body"><p><strong>Family History:</strong> <?php echo $record['family_history'] ? 'Yes' : 'No'; ?></p><p><?php if ($risks) { foreach ($risks as $risk) { ?><span class="gl-tag"><?php echo ucwords(str_replace('_', ' ', html_escape($risk))); ?></span><?php } } else { ?><span class="text-muted">No significant risk factors documented</span><?php } ?></p><hr><strong>Clinical Notes</strong><p><?php echo gl_show($record['notes']); ?></p></div></div></div></div>
        <div class="box gl-detail-box"><div class="box-header with-border"><h3 class="box-title">IOP History</h3><button class="btn btn-primary btn-sm pull-right no-print" data-toggle="modal" data-target="#iopModal"><i class="fa fa-plus"></i> Add IOP Reading</button></div><div class="box-body table-responsive"><table class="table table-striped"><thead><tr><th>Date</th><th>OD</th><th>OS</th><th>Method</th><th>Clinician</th><th>Notes</th></tr></thead><tbody><?php if (!$history) { ?><tr><td colspan="6" class="text-center text-muted">No IOP readings recorded.</td></tr><?php } ?><?php foreach ($history as $reading) { ?><tr><td><?php echo date('d M Y, h:i A', strtotime($reading['measured_at'])); ?></td><td><?php echo gl_show($reading['iop_od']); ?></td><td><?php echo gl_show($reading['iop_os']); ?></td><td><?php echo strtoupper(html_escape($reading['method'])); ?></td><td><?php echo html_escape(trim($reading['doctor_name'] . ' ' . $reading['doctor_surname'])); ?></td><td><?php echo gl_show($reading['notes']); ?></td></tr><?php } ?></tbody></table></div></div>
        <div class="box gl-detail-box"><div class="box-header"><h3 class="box-title">Current Medications</h3></div><div class="box-body"><table class="table table-bordered"><thead><tr><th>Medication</th><th>Dosage</th><th>Frequency</th><th>Eye</th></tr></thead><tbody><?php if (!$medications) { ?><tr><td colspan="4" class="text-center text-muted">No current medications.</td></tr><?php } ?><?php foreach ($medications as $med) { ?><tr><td><?php echo html_escape($med['name']); ?></td><td><?php echo html_escape($med['dosage']); ?></td><td><?php echo strtoupper(html_escape($med['frequency'])); ?></td><td><?php echo html_escape($med['eye']); ?></td></tr><?php } ?></tbody></table></div></div>
        <form class="no-print" method="post" action="<?php echo site_url('admin/glaucoma/delete/' . $record['id']); ?>" onsubmit="return confirm('Delete this glaucoma record and all IOP history?');" style="display:inline"><?php echo $this->customlib->getCSRF(); ?><button class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button></form> <a class="btn btn-default no-print" href="<?php echo site_url('admin/glaucoma'); ?>"><i class="fa fa-arrow-left"></i> Back to records</a>
    </section>
</div>
<div class="modal fade" id="iopModal"><div class="modal-dialog"><div class="modal-content"><form method="post" action="<?php echo site_url('admin/glaucoma/add_iop/' . $record['id']); ?>"><?php echo $this->customlib->getCSRF(); ?><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Add IOP Reading</h4></div><div class="modal-body"><div class="row"><div class="form-group col-xs-6"><label>OD (mmHg)</label><input type="number" step="0.1" min="0" class="form-control" name="iop_od"></div><div class="form-group col-xs-6"><label>OS (mmHg)</label><input type="number" step="0.1" min="0" class="form-control" name="iop_os"></div><div class="form-group col-xs-6"><label>Method</label><select class="form-control" name="iop_method"><option value="goldmann">Goldmann</option><option value="nct">NCT</option><option value="icare">iCare</option><option value="tono_pen">Tono-Pen</option></select></div><div class="form-group col-xs-6"><label>Time</label><input type="datetime-local" name="measured_at" class="form-control" value="<?php echo date('Y-m-d\TH:i'); ?>"></div><div class="form-group col-xs-12"><label>Notes</label><input class="form-control" name="iop_notes"></div></div></div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button><button class="btn btn-primary"><i class="fa fa-save"></i> Save Reading</button></div></form></div></div></div>
